# Generated by Django 6.0.5 on 2026-05-25 17:20

import django.core.validators
import django.db.models.deletion
import taller.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_ruc', models.CharField(help_text='Ingrese los 10 dígitos de la cédula o 13 del RUC.', max_length=13, unique=True, validators=[taller.validators.validar_cedula_ruc_ecuador], verbose_name='Cédula/RUC')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'En reparación'), ('INACTIVO', 'No disponible / Ausente')], default='DISPONIBLE', max_length=15)),
            ],
            options={
                'verbose_name': 'Mecánico',
                'verbose_name_plural': 'Mecánicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloCompatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de Moto/Tricimoto')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo de Moto/Tricimoto')),
            ],
            options={
                'verbose_name': 'Modelo de Compatibilidad',
                'verbose_name_plural': 'Modelos de Compatibilidad',
                'ordering': ['marca', 'modelo'],
                'unique_together': {('marca', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº de Orden')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_prometida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Prometida de Entrega')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Entrega')),
                ('kilometraje', models.IntegerField(default=0, verbose_name='Kilometraje')),
                ('nivel_combustible', models.CharField(default='1/4', help_text='Ej: Vacío, 1/4, 1/2, 3/4, Lleno', max_length=20, verbose_name='Nivel de Gasolina')),
                ('observaciones_recepcion', models.TextField(blank=True, verbose_name='Falla Reportada / Observaciones')),
                ('checklist_json', models.JSONField(blank=True, default=dict, help_text='Almacena estado de accesorios y daños físicos.', verbose_name='Checklist Visual')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico Técnico')),
                ('mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de Mano de Obra')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Reparación'), ('ESPERANDO_REPUESTOS', 'Esperando Repuestos'), ('TERMINADO', 'Trabajo Terminado (Por Entregar)'), ('ENTREGADO', 'Entregado y Facturado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='taller.mecanico')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Repuesto')),
                ('categoria', models.CharField(choices=[('MOTOR', 'Motor y Componentes'), ('ELECTRICO', 'Sistema Eléctrico'), ('TRANSMISION', 'Transmisión y Embrague'), ('SUSPENSION', 'Suspensión y Amortiguadores'), ('FRENOS', 'Sistema de Frenos'), ('CARROCERIA', 'Chasis, Plásticos y Espejos'), ('LLANTAS', 'Llantas y Cámaras'), ('ACEITES', 'Aceites y Lubricantes'), ('VARIOS', 'Otros / Accesorios')], max_length=20, verbose_name='Categoría')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca del Repuesto')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Estante B - Fila 3', max_length=50, verbose_name='Ubicación (Percha/Estante)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=5, verbose_name='Stock Mínimo (Alerta)')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Venta (PVP)')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='Aplica IVA')),
                ('compatibilidades', models.ManyToManyField(blank=True, related_name='repuestos', to='taller.modelocompatibilidad', verbose_name='Compatible con')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRepuestoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_historico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Cobrado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_utilizados', to='taller.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.repuesto')),
            ],
            options={
                'verbose_name': 'Repuesto Utilizado',
                'verbose_name_plural': 'Repuestos Utilizados',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MOTO', 'Motocicleta'), ('TRICIMOTO', 'Tricimoto')], default='MOTO', max_length=15)),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('placa', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Placa')),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Motor')),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Chasis (VIN)')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='taller.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='taller.vehiculo'),
        ),
    ]
