# Generated by Django 6.0.5 on 2026-06-01 02:30

import django.db.models.deletion
import taller.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[taller.validators.validar_cedula_ruc_ecuador], verbose_name='Cédula')),
                ('cargo', models.CharField(choices=[('ADMIN_RRHH', 'Talento Humano'), ('OPERATIVO_RECEPCION', 'Recepcionista Taller'), ('VENDEDOR', 'Vendedor / Cajero'), ('BODEGUERO', 'Bodeguero'), ('GERENTE', 'Gerente')], max_length=30, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sueldo Base')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión aplicable si es mecánico o vendedor.', max_digits=5, verbose_name='Porcentaje Comisión (%)')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='taller.empleado')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='taller.mecanico')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('sueldo_basico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo Básico')),
                ('comisiones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Comisiones')),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Bonificaciones')),
                ('deducciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Deducciones (IESS, multas)')),
                ('total_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total Neto a Pagar')),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='taller.empleado')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='taller.mecanico')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-fecha_fin'],
            },
        ),
    ]
