# Generated by Django 6.0.5 on 2026-06-01 02:30

import django.db.models.deletion
import taller.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_empleado_horario_nomina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('documento_referencia', models.CharField(blank=True, max_length=50, verbose_name='Nº Factura Proveedor')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra a Proveedor',
                'verbose_name_plural': 'Compras a Proveedores',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[taller.validators.validar_cedula_ruc_ecuador], verbose_name='RUC')),
                ('nombre_empresa', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INVENTARIO', 'Predicción de Compra / Stock'), ('MANTENIMIENTO', 'Sugerencia de Mantenimiento Preventivo a Clientes')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(verbose_name='Recomendación Detallada de Negocio')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recomendación IA',
                'verbose_name_plural': 'Recomendaciones IA',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('04', 'RUC (Persona Natural/Jurídica)'), ('05', 'Cédula de Identidad'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'Identificación del Exterior')], default='05', max_length=2, verbose_name='Tipo Identificación SRI'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='facturada',
            field=models.BooleanField(default=False, verbose_name='Facturada'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='tarifa_iva',
            field=models.CharField(choices=[('0', '0% (Exento / No Objeto)'), ('2', '15% (Tarifa Estándar de IVA en Ecuador)'), ('6', 'No aplica IVA')], default='2', max_length=2, verbose_name='Tarifa IVA SRI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula_ruc',
            field=models.CharField(help_text='Ingrese los 10 dígitos de la cédula, 13 del RUC o identificación.', max_length=13, unique=True, validators=[taller.validators.validar_cedula_ruc_ecuador], verbose_name='Cédula/RUC/Pasaporte'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='aplica_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA (Obs.)'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código / SKU (Código Principal SRI)'),
        ),
        migrations.CreateModel(
            name='DetalleCompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='taller.compraproveedor')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.repuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Nº Factura')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PAGADA', max_length=10)),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal IVA 15%')),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal IVA 0%')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Descuento')),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Total IVA')),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Neto a Pagar')),
                ('clave_acceso', models.CharField(blank=True, max_length=49, null=True, unique=True, verbose_name='Clave de Acceso (49 dígitos)')),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, null=True, verbose_name='Número de Autorización SRI')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización SRI')),
                ('estado_sri', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado al SRI'), ('AUTORIZADO', 'Autorizado y Vigente'), ('RECHAZADO', 'Rechazado por el SRI'), ('DEVUELTO', 'Devuelto / Con Errores')], default='PENDIENTE', max_length=15, verbose_name='Estado SRI')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas (Test)'), ('2', 'Producción (Real)')], default='1', max_length=1, verbose_name='Ambiente SRI')),
                ('tipo_emision', models.CharField(default='1', max_length=1, verbose_name='Tipo Emisión SRI')),
                ('xml_firmado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta XML Firmado')),
                ('pdf_ride', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta PDF RIDE')),
                ('mensajes_error_sri', models.JSONField(blank=True, default=list, verbose_name='Errores / Respuestas SRI')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='taller.cliente')),
                ('orden_trabajo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='taller.ordentrabajo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_vendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_mano_obra', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Servicio (Mano Obra)')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taller.repuesto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='taller.factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('01', 'Sin Utilización del Sistema Financiero (Efectivo)'), ('16', 'Tarjeta de Débito'), ('19', 'Tarjeta de Crédito'), ('20', 'Otros con Utilización del Sistema Financiero (Transferencia/Apps)')], default='01', max_length=2, verbose_name='Método de Pago SRI')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='taller.factura')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO_COMPRA', 'Ingreso por Compra a Proveedor'), ('EGRESO_VENTA', 'Egreso por Venta Directa (POS)'), ('EGRESO_TALLER', 'Egreso por Reparación en Taller (OT)'), ('INGRESO_DEVOLUCION', 'Ingreso por Devolución de Cliente'), ('AJUSTE_POSITIVO', 'Ajuste de Inventario (Sobrante)'), ('AJUSTE_NEGATIVO', 'Ajuste de Inventario (Faltante/Merma)')], max_length=20)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo / Observación')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='taller.repuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='taller.proveedor'),
        ),
    ]
